apiVersion: v1
kind: Pod
metadata:
  name: gs-sbd-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: jiaozhu/gs-spring-boot-docker:0.1
      name: gs-sbd
      ports:
        - containerPort: 8080
          protocol: TCP
